### ISSUE TITLE
RedisHandler::clearToken 方法第二个参数类型有误

### ISSUE THREAD

**Issue by lozhu** [Tinywan/webman-jwt#7]
RedisHandler::clearToken($config['cache_token_pre'], self::getCurrentId());
参数第二个类型是string,而self::getCurrendId()方法返回的是Int,报类型错误
php版本8.0

**Comment by lozhu** [comment]
msg
: 
"Tinywan\\Jwt\\RedisHandler::clearToken(): Argument #2 ($uid) must be of type string, int given, called in /Users/lianzhang/Sites/newadmin/vendor/tinywan/jwt/src/JwtToken.php on line 363"
traces
: 
"TypeError: Tinywan\\Jwt\\RedisHandler::clearToken(): Argument #2 ($uid) must be of type string, int given, called in /Users/lianzhang/Sites/newadmin/vendor/tinywan/jwt/src/JwtToken.php on line 363 and defined in /Users/lianzhang/Sites/newadmin/vendor/tinywan/jwt/src/RedisHandler.php:62\nStack trace:\n#0 /Users/lianzhang/Sites/newadmin/vendor/tinywan/jwt/src/JwtToken.php(363): Tinywan\\Jwt\\RedisHandler::clearToken('JWT:TOKEN:', 1)\n#1 /Users/lianzhang/Sites/newadmin/app/admin/controller/AuthController.php(73): Tinywan\\Jwt\\JwtToken::clear()\n#2 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/App.php(293): app\\admin\\controller\\AuthController->logout(Object(support\\Request))\n#3 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/App.php(317): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#4 /Users/lianzhang/Sites/newadmin/vendor/nsp-team/webman-throttler/src/Middleware/ThrottlerMiddleware.php(45): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#5 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/App.php(309): NspTeam\\WebmanThrottler\\Middleware\\ThrottlerMiddleware->process(Object(support\\Request), Object(Closure))\n#6 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/App.php(531): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#7 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/App.php(128): Webman\\App::findRoute(Object(Workerman\\Connection\\TcpConnection), '/api/v1/admin/l...', 'POST/api/v1/adm...', Object(support\\Request))\n#8 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Connection/TcpConnection.php(638): Webman\\App->onMessage(Object(Workerman\\Connection\\TcpConnection), Object(support\\Request))\n#9 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Events/Select.php(311): Workerman\\Connection\\TcpConnection->baseRead(Resource id #258)\n#10 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Worker.php(2467): Workerman\\Events\\Select->loop()\n#11 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Worker.php(1578): Workerman\\Worker->run()\n#12 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Worker.php(1420): Workerman\\Worker::forkOneWorkerForLinux(Object(Workerman\\Worker))\n#13 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Worker.php(1394): Workerman\\Worker::forkWorkersForLinux()\n#14 /Users/lianzhang/Sites/newadmin/vendor/workerman/workerman/Worker.php(560): Workerman\\Worker::forkWorkers()\n#15 /Users/lianzhang/Sites/newadmin/vendor/workerman/webman-framework/src/support/App.php(124): Workerman\\Worker::runAll()\n#16 /Users/lianzhang/Sites/newadmin/start.php(4): support\\App::run()\n#17 {main}"

**Comment by Tinywan** [comment]
已修复，请更新到：`v1.5.2`
